services:
  pubsubdev:
    build:
      context: .
      dockerfile: Dockerfile-devcontainer
      args:
        ROS_DISTRO: jazzy
    volumes:
      - ./ros/publishing:/ws/publishing:rw
      - ./ros/subscribing:/ws/subscribing:rw
      - ./README.md:/ws/README.md:rw
    environment:
      - PYTHONUNBUFFERED=1
    command: ["/bin/sh", "-c", "sleep infinity"] 