ARG ROS_DISTRO=jazzy
FROM ros:${ROS_DISTRO}

RUN apt-get update -qq \
    && apt-get install -y \
    ros-${ROS_DISTRO}-std-msgs \
    && rm -rf /var/lib/apt/lists/*

COPY entrypoint.bash /entrypoint.bash
RUN chmod +x /entrypoint.bash
ENTRYPOINT ["/entrypoint.bash"]

ENV ROS_WORKSPACE=/ws
WORKDIR ${ROS_WORKSPACE}
COPY ./subscribing ${ROS_WORKSPACE}/subscribing
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build

COPY README.md /ws/README.md

CMD ["ros2", "run", "subscribing", "subscribing"]