ARG ROS_DISTRO=jazzy
FROM ros:${ROS_DISTRO}

COPY ./ros/entrypoint.bash /entrypoint.bash
RUN chmod +x /entrypoint.bash
ENTRYPOINT ["/entrypoint.bash"]

ENV ROS_WORKSPACE=/ws
WORKDIR ${ROS_WORKSPACE}

COPY ./ros/publishing/ ${ROS_WORKSPACE}/publishing
COPY ./ros/subscribing/ ${ROS_WORKSPACE}/subscribing
COPY README.md ${ROS_WORKSPACE}/README.md

RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build --symlink-install


CMD ["/bin/bash"]