ARG ROS_DISTRO=jazzy
FROM ros:${ROS_DISTRO}

COPY entrypoint.bash /entrypoint.bash
RUN chmod +x /entrypoint.bash
ENTRYPOINT ["/entrypoint.bash"]

ENV ROS_WORKSPACE=/ws
WORKDIR ${ROS_WORKSPACE}
COPY ./publishing/ ${ROS_WORKSPACE}/publishing
COPY ./publishing/README.md /ws/README.md

RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build --symlink-install

CMD ["ros2", "run", "publishing", "publishing"]