services:
  publishing:
    build:
      context: ../ros
      dockerfile: ../part3/Dockerfile-publishing
      args:
        ROS_DISTRO: jazzy
    volumes:
      # overwrite only specific files in the container, add new node-script
      - ./publishing/watchdog_dev.py:/ws/src/publishing/publishing/main.py:rw
      - ./publishing/node.py:/ws/src/publishing/publishing/node.py:rw
      - ./publishing/launch/publishing.launch.py:/ws/src/publishing/launch/publishing.launch.py:rw
    environment:
      - PYTHONUNBUFFERED=1

  subscribing:
    build:
      context: ../ros
      dockerfile: ../part2/Dockerfile-subscribing
      args:
        ROS_DISTRO: jazzy
    volumes:
      - ../ros/subscribing:/ws/src/subscribing:rw
    environment:
      - PYTHONUNBUFFERED=1