ARG ROS_DISTRO=jazzy
FROM ros:${ROS_DISTRO}

RUN apt-get update && \
    apt-get install python3-watchdog  && \
    rm -rf /var/lib/apt/lists/*

COPY entrypoint.bash /entrypoint.bash
RUN chmod +x /entrypoint.bash
ENTRYPOINT ["/entrypoint.bash"]

ENV ROS_WORKSPACE=/ws
WORKDIR ${ROS_WORKSPACE}
COPY ./publishing/ ${ROS_WORKSPACE}/publishing
COPY ./publishing/README.md /ws/README.md

RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build --symlink-install

CMD ["ros2", "launch", "publishing", "publishing.launch.py"]
