ARG ROS_DISTRO=jazzy
FROM ros:${ROS_DISTRO}

COPY entrypoint.bash /entrypoint.bash
RUN chmod +x /entrypoint.bash
ENTRYPOINT ["/entrypoint.bash"]

ENV ROS_WORKSPACE=/ws
WORKDIR ${ROS_WORKSPACE}
COPY ./subscribing/ ${ROS_WORKSPACE}/subscribing
COPY ./subscribing/README.md /ws/README.md

RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build

CMD ["ros2", "launch", "subscribing", "subscribing.launch.py"]